### ISSUE TITLE
VSCode Auto Imports

### ISSUE THREAD

**Issue by adstotz** [fwcd/vscode-kotlin-ide#18] opened 2019-10-12 17:24 UTC
Unlike when editing .java files, it seems that auto-importing does not work with Kotlin and this plug-in. For example, I include a dependency in my gradle.build file, the library appears in my Java Dependencies list, but referencing a class in that library from within a .kt file does not trigger an import of the class from the library. The class remains unresolved.

All around, this plug-in seems very promising, but this feature gap prevents me from using VS Code with the Kotlin language. If auto-importing worked just as it does with Java, that would be a tremendous productivity enhancement!

**Comment by fwcd** [comment] 2019-10-15 02:25
Duplicate of https://github.com/fwcd/kotlin-language-server/issues/10.

**Closed by fwcd** 2019-10-15 02:25 UTC
Labels: duplicate, enhancement
